/***********************************************************************/
/*                                                                     */
/*  FILE        :lowsrc.h                                              */
/*  DATE        :Tue, Nov 09, 2010                                     */
/*  DESCRIPTION :Header file of I/O Stream file                        */
/*  CPU TYPE    :SH7760                                                */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
/*Number of I/O Stream*/
#define IOSTREAM 20
