/***********************************************************************/
/*                                                                     */
/*  FILE        :Sensor.c                                              */
/*  DATE        :Tue, Nov 09, 2010                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :SH7760                                                */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  


//#include "typedefine.h"
#ifdef __cplusplus
//#include <ios>                        // Remove the comment when you use ios
//_SINT ios_base::Init::init_cnt;       // Remove the comment when you use ios
#endif
#include "Sensor.h"

extern const unsigned int MAX_NUMBER_OF_SAMPLES;

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void mainLoopDriver()
{
	unsigned int sensorValue;
	unsigned char status = 1;
	while (1) {
		status = readSensor(&sensorValue);
		if (status == STATUS_STOPPED) {
			break;
		} else if (status == STATUS_FAILED) {
			reportSensorFailure();
			break;
		}
		handleSensorValue(sensorValue);
	}
	finalize();
}

void main(void)
{
	mainLoopDriver();
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
